const HANDLE_CHANGE_INPUT = 'HANDLE_CHANGE_INPUT',
	HANDLE_CHANGE_FILE = 'UPDATE_FILE',
	HANDLE_CHANGE_TEXT_MEME = 'HANDLE_CHANGE_TEXT_MEME',
	ADD_NEW_TEXT_MEME = 'ADD_NEW_TEXT_MEME';

export { HANDLE_CHANGE_INPUT, HANDLE_CHANGE_FILE, HANDLE_CHANGE_TEXT_MEME, ADD_NEW_TEXT_MEME };
